# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 15:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reusable_blogprj', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='content',
            field=models.TextField(default='My blog post'),
        ),
    ]
